/* Admin workspace: user roles, granular access and audit history. */
(function(){
"use strict";
const $=id=>document.getElementById(id),sb=()=>window.supabaseClient;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const ROLES=["manager","accounts","store","staff"];
const PERMS=["sales","customers","finance","reports","inventory","dispatch","purchases","requests","approvals"];
const LABELS={sales:"Sales orders",customers:"Customer records",finance:"Invoices & payments",reports:"Business reports",inventory:"Stock",dispatch:"Dispatch operations",purchases:"Purchases",requests:"Customer requests",approvals:"Approve pending changes"};
const TAB_PERMISSION={orders:"sales",sales:"dispatch",parties:"customers",products:"customers",balances:"customers",quotations:"sales",priceboard:"sales",purchase:"purchases",inventory:"inventory",invoices:"finance",payments:"finance",financeCenter:"finance",reports:"reports",requests:"requests",approvals:"approvals",notifications:"requests"};
let activeRole="",activePermissions=new Set();
const style=document.createElement("style");style.textContent='#adminAccess .access-check{display:inline-grid;place-items:center;min-width:32px;min-height:32px;cursor:pointer}#adminAccess input[type=checkbox]{width:17px;height:17px;accent-color:#255c4e;cursor:pointer}#adminAccess .errorbox{padding:14px;background:#fff2f1;border:1px solid #f1cfcb;border-radius:10px;color:#8d342d}#adminAccess .access-feedback{min-height:24px;padding:8px 10px;margin:7px 0;color:#255c4e;background:#eef7f2;border-radius:8px;font-size:13px;font-weight:650}#adminAccess .access-feedback:empty{display:none}#adminAccess .access-feedback.is-error{color:#8d342d;background:#fff2f1}#adminAccess table{min-width:850px}';document.head.appendChild(style);
async function rpc(name,args={}){const r=await sb().rpc(name,args);if(r.error)throw r.error;return r.data}
function ensure(){
 const ng=document.querySelector('.nav-group[data-group="hr"] .nav-items');
 if(ng&&!document.querySelector('[data-tab="adminAccess"]')){const b=document.createElement("button");b.className="tab";b.dataset.tab="adminAccess";b.innerHTML='<span class="navIcon">♙</span><span>Roles &amp; access</span>';ng.appendChild(b);b.addEventListener("click",e=>{e.preventDefault();e.stopImmediatePropagation();window.showTab("adminAccess")},true)}
 if(!$("adminAccess")){const s=document.createElement("section");s.id="adminAccess";s.className="hidden";$("payroll")?.after(s)||$("purchase")?.after(s)}
}
function roleOptions(current){return ROLES.map(x=>`<option value="${x}" ${x===current?"selected":""}>${x[0].toUpperCase()+x.slice(1)}</option>`).join("")}
async function drawAccess(){
 const s=$("adminAccess");if(!s)return;
 s.innerHTML='<div class="panel"><h2>Loading access controls…</h2></div>';
 try{
  const data=await rpc("admin_get_role_data"),users=data.users||[],grants=data.permissions||[];
  const rows=users.map(u=>`<tr><td><b>${esc(u.email||"No email")}</b><div class="small muted">${esc(u.user_id)}</div></td><td><span class="pill">${esc(u.role)}</span></td><td>${u.role==="admin"?"Full system access":"Assigned role access"}</td><td>${u.role==="admin"?"Protected":`<select data-user-role="${esc(u.email)}" aria-label="Change role for ${esc(u.email)}">${roleOptions(u.role)}</select>`}</td></tr>`).join("");
  const matrix=ROLES.map(role=>`<tr><th scope="row">${role[0].toUpperCase()+role.slice(1)}<div class="small muted">${role==="staff"?"Basic operating access":role==="manager"?"Team oversight and approvals":role==="accounts"?"Finance and reporting": "Stock and fulfilment"}</div></th>${PERMS.map(p=>{const on=grants.some(g=>g.role===role&&g.permission===p&&g.allowed);return `<td class="center"><label class="access-check"><input type="checkbox" data-grant-role="${role}" data-grant-perm="${p}" ${on?"checked":""} aria-label="${esc(role)}: ${esc(LABELS[p])}"><span class="sr-only">${esc(role)}: ${esc(LABELS[p])}</span></label></td>`}).join("")}</tr>`).join("");
  s.innerHTML=`<div class="panel"><div class="sd-section-title"><div><h2>Roles &amp; access</h2><p>Give each team member only the access their work requires.</p></div><span class="tag">Admin only</span></div><div class="notice"><b>Admin</b> has full access, including payroll and role management. This form grants access to an existing Supabase Auth account; it does not create or invite an account. Create the account first under Supabase Authentication → Users.</div><form id="adminAddUser" class="grid"><div class="field"><label for="adminUserEmail">User email</label><input id="adminUserEmail" type="email" autocomplete="email" required placeholder="name@company.com"></div><div class="field"><label for="adminUserRole">Role</label><select id="adminUserRole">${roleOptions("staff")}</select></div><div class="field" style="align-self:end"><button id="adminAddUserButton" class="primary" type="submit">Grant / update access</button></div></form><p id="adminAccessStatus" class="access-feedback" aria-live="polite"></p><h3>Team members</h3>${tbl(["Account","Current role","Access","Change role"],rows)}<h3 style="margin-top:24px">Role permissions</h3><p class="small muted">Admin permissions are fixed. Payroll stays admin-only. Updates save immediately.</p><div class="tablewrap"><table><thead><tr><th>Role</th>${PERMS.map(p=>`<th>${esc(LABELS[p])}</th>`).join("")}</tr></thead><tbody>${matrix}</tbody></table></div></div>`;
  const feedback=$("adminAccessStatus"),emailInput=$("adminUserEmail"),submit=$("adminAddUserButton");
  const say=(message,isError=false)=>{feedback.textContent=message;feedback.classList.toggle("is-error",isError)};
  submit.addEventListener("click",()=>{if(!emailInput.value.trim())say("Enter the email of an existing Supabase Auth user.",true);else if(!emailInput.checkValidity())say("Enter a valid email address.",true);else say("Saving access…")});
  $("adminAddUser").onsubmit=async e=>{e.preventDefault();submit.disabled=true;try{await rpc("admin_set_user_role",{p_email:emailInput.value.trim(),p_role:$("adminUserRole").value});await drawRole();await drawAccess();if($("adminAccessStatus")){const out=$("adminAccessStatus");out.textContent="Access saved.";out.classList.remove("is-error")}}catch(err){say(err.message||"Could not save access.",true)}finally{if($("adminAddUserButton"))$("adminAddUserButton").disabled=false}};
  s.querySelectorAll("[data-user-role]").forEach(el=>el.onchange=async()=>{try{await rpc("admin_set_user_role",{p_email:el.dataset.userRole,p_role:el.value});await drawRole();await drawAccess();if($("adminAccessStatus"))$("adminAccessStatus").textContent="Role updated."}catch(err){if($("adminAccessStatus")){const out=$("adminAccessStatus");out.textContent=err.message||"Could not update role.";out.classList.add("is-error")}await drawAccess()}});
  s.querySelectorAll("[data-grant-role]").forEach(el=>el.onchange=async()=>{const status=$("adminAccessStatus");el.disabled=true;try{await rpc("admin_set_role_permission",{p_role:el.dataset.grantRole,p_permission:el.dataset.grantPerm,p_allowed:el.checked});status.textContent="Permission saved."}catch(err){el.checked=!el.checked;status.textContent=err.message||"Could not save permission."}finally{el.disabled=false}});
 }catch(err){s.innerHTML=`<div class="panel"><h2>Roles &amp; access</h2><div class="errorbox">${esc(err.message||"Access controls could not be loaded.")}<br>Apply <code>supabase/15_admin_role_management.sql</code> in Supabase SQL Editor, then refresh.</div></div>`}
}
function tbl(headers,rows){return `<div class="tablewrap"><table><thead><tr>${headers.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${rows||'<tr><td colspan="8" class="empty">No team members are configured yet.</td></tr>'}</tbody></table></div>`}
async function drawAudit(){const s=$("auditCenter");if(!s)return;const r=await sb().from("audit_log").select("*").order("at",{ascending:false}).limit(200);if(r.error){s.innerHTML=`<div class="panel"><h2>Audit Center</h2><p class="errorbox">${esc(r.error.message)}</p></div>`;return}const rows=(r.data||[]).map(x=>`<tr><td>${esc(x.at)}</td><td>${esc(x.table_name)}</td><td><span class="pill">${esc(x.action)}</span></td><td>${esc(x.user_id||"")}</td><td><code>${esc(JSON.stringify(x.row_data||{}).slice(0,180))}</code></td></tr>`);s.innerHTML='<div class="panel"><div class="sd-section-title"><div><h2>Audit Center</h2><p>Business-change history for review and troubleshooting.</p></div><span class="tag">Last 200 events</span></div><div class="tablewrap"><table><thead><tr><th>Time</th><th>Table</th><th>Action</th><th>User</th><th>Changed data</th></tr></thead><tbody>'+(rows.join("")||'<tr><td colspan="5" class="empty">No audit events.</td></tr>')+'</tbody></table></div></div>'}
function applyAccess(){document.querySelectorAll(".tab[data-tab]").forEach(b=>{const t=b.dataset.tab,p=TAB_PERMISSION[t],adminOnly=["payroll","adminAccess","auditCenter"].includes(t),allowed=activeRole==="admin"||(!adminOnly&&!!activeRole&&(!p||activePermissions.has(p)||(p==="dispatch"&&activePermissions.has("sales"))||(p==="requests"&&activePermissions.has("finance"))));b.classList.toggle("hidden",!allowed)});document.querySelectorAll("[data-go]").forEach(b=>{const p=TAB_PERMISSION[b.dataset.go];b.classList.toggle("hidden",activeRole!=="admin"&&(!activeRole||!!p&&!activePermissions.has(p)))});document.querySelectorAll('.nav-group[data-group="finance"],.nav-group[data-group="sales"],.nav-group[data-group="purchase"],.nav-group[data-group="operations"],.nav-group[data-group="hr"]').forEach(g=>{const visible=[...g.querySelectorAll(".tab")].some(b=>!b.classList.contains("hidden"));g.classList.toggle("hidden",!visible)});}
async function drawRole(){try{const r=await sb().rpc("get_dashboard_role");if(r.error||!r.data)return;activeRole=r.data.role||"staff";activePermissions=new Set(r.data.permissions||[]);if(activeRole==="admin")ensure();applyAccess();const tag=$("dashboard")?.querySelector(".sd-section-title .tag");if(tag)tag.textContent="Role: "+activeRole}catch(e){}}
let roleTimer=setInterval(()=>{const box=$("loginBox");if(box&&!box.classList.contains("hidden")){activeRole="";activePermissions.clear();applyAccess();return}if(!activeRole)drawRole()},1200);
const old=window.showTab;window.showTab=function(t){const p=TAB_PERMISSION[t];if((t==="adminAccess"||t==="auditCenter"||t==="payroll")&&activeRole!=="admin")t="dashboard";else if(p&&activeRole!=="admin"&&!activePermissions.has(p)&&!(p==="dispatch"&&activePermissions.has("sales")))t="dashboard";old(t);document.querySelectorAll("section[id]").forEach(x=>x.classList.toggle("hidden",x.id!==t));$(t)?.classList.remove("hidden");if(t==="auditCenter")drawAudit();if(t==="adminAccess")drawAccess()};
})();
